# SignPorts Configuration

# The text that should be on the first line of a sign to create a SignPort
signport-identifier: "[SignPort]"

# Menu name for the SignPorts GUI
menu-name: "SignPorts Menu"

# Minimum level required to use a SignPort
signport-level-restriction: 10

# The item to represent SignPorts in GUIs or as markers (if applicable)
signport-icon: "OAK_SIGN"

# Maximum number of SignPorts a player can create
max-signports-per-player: 1

# Cooldown between SignPort uses (in seconds)
teleport-cooldown: 10

# Whether to allow cross-world teleportation
allow-cross-world: true

# Messages
messages:
  creation-success: "SignPort %signport% created successfully!"
  removal-success: "SignPort %signport% removed successfully!"
  teleport-success: "You've been teleported to %signport%!"

# Legacy configuration (consider removing if not used)
welcomeLine: "[Signport]"
warps: {}