name: SignPorts
version: 1.0.1
main: net.farhaven.SignPorts.SignPorts
api-version: '1.20'
description: A plugin for creating and using sign-based teleportation ports
author: SquilliamGhost
website: https://www.farhaven.net

commands:
  signport:
    description: Main command for SignPorts
    usage: /signport <create|list|remove|teleport|gui|setname|setdesc|setitem|reload> [arguments]
    aliases: [sp]
  signportmenu:
    description: Open the SignPorts menu
    usage: /signportmenu
    aliases: [pshop, pshops, playershops, splist, spmenu]
  confirm:
    description: Confirm a SignPort action
    usage: /confirm
  setname:
    description: Set the name of your SignPort
    usage: /setname <new name>
  setdesc:
    description: Set the description of your SignPort
    usage: /setdesc <new description>

depend: [PlaceholderAPI]
soft-depend: [GriefDefender]

permissions:
  signports.create:
    description: Allows creation of SignPorts
    default: op
  signports.use:
    description: Allows usage of SignPorts
    default: true
  signports.list:
    description: Allows listing of SignPorts
    default: true
  signports.remove:
    description: Allows removal of SignPorts
    default: op
  signports.teleport:
    description: Allows teleportation to SignPorts
    default: true
  signports.gui:
    description: Allows using the SignPort GUI
    default: true
  signports.admin:
    description: Gives access to all SignPorts commands and features
    default: op
    children:
      signports.create: true
      signports.use: true
      signports.list: true
      signports.remove: true
      signports.teleport: true
      signports.gui: true